name: "1.1.1"

variables:
  ${{ if startsWith(variables['Build.SourceBranchName'], 'release') }}:
    buildIncrement: $[counter(variables['ReleaseVersion'], 0)]
    buildVersion: "$(ReleaseVersion).$(buildIncrement)"
    buildConfiguration: 'Release'
  ${{ if not(startsWith(variables['Build.SourceBranchName'], 'release')) }}:
    buildIncrement: $[counter(variables['DevelopmentVersion'], 0)]
    buildVersion: "$(DevelopmentVersion).$(buildIncrement)-preview"
    buildConfiguration: 'Debug'

trigger:
  branches:
    include:
    - development
    - release
  paths:
   exclude:
   - BuildPipelines/*
   include:
   - Gamification.Platform/*

resources:
  repositories:
  - repository: 'Infrastructure'
    type: git
    name: 'Operations/Infrastructure'
    ref: 'refs/heads/development'

jobs:
- job: BuildNETCore
  displayName: 'Build and Push .NET Core Assemblies'
  pool:
    VmImage: 'windows-2019'
  
  steps:

  - powershell: |
      Write-Host "##vso[build.updatebuildnumber]$(buildVersion)"
    displayName: "Set Build Number"

  - template: BuildPipelines\Templates\Steps-BuildAndPushNetCoreMultiProject.yml@Infrastructure
    parameters:
      BuildConfiguration: $(buildConfiguration)
      Projects: |
        **/Gamification.Platform.Common.Core.csproj
        **/Gamification.Platform.Common.Display.csproj
        **/Gamification.Platform.Common.Extensions.csproj
        **/Gamification.Platform.Common.csproj
        **/Gamification.Platform.SDK.CSharp.csproj
      PackagesToPack: |
        **/Gamification.Platform.Common.Core.csproj;
        **/Gamification.Platform.Common.Display.csproj;
        **/Gamification.Platform.Common.Extensions.csproj;
        **/Gamification.Platform.Common.csproj;
        **/Gamification.Platform.SDK.CSharp.csproj;
      IncludeReferencedProjects: true
      ExternalNuget: true