name: "1.1.1"

variables:
  ${{ if startsWith(variables['Build.SourceBranchName'], 'release') }}:
    buildIncrement: $[counter(variables['ReleaseVersion'], 0)]
    buildVersion: "$(ReleaseVersion).$(buildIncrement)"
  ${{ if not(startsWith(variables['Build.SourceBranchName'], 'release')) }}:
    buildIncrement: $[counter(variables['DevelopmentVersion'], 0)]  
    buildVersion: "$(DevelopmentVersion).$(buildIncrement)-preview"

trigger:
  branches:
    include:
    - development
    - release
  paths:
    include:
    - src/Gamification.Platform.Common.Extensions/*

resources:
  repositories:
  - repository: 'Infrastructure'
    type: git
    name: 'Operations/Infrastructure'
    ref: 'refs/heads/development'

jobs:
- job: BuildNETCore
  displayName: 'Build and Push .NET Core Assemblies'
  pool:
    VmImage: 'windows-2019'  
  
  steps:

  - powershell: |
      Write-Host "##vso[build.updatebuildnumber]$(buildVersion)"
    displayName: "Set Build Number"

  - template: BuildPipelines\Templates\Steps-BuildAndPushNetCore.yml@Infrastructure
    parameters:
      ProjectFolder: 'src/Gamification.Platform.Common.Extensions'
      ${{ if not(startsWith(variables['Build.SourceBranchName'], 'release')) }}:
        BuildConfiguration: 'Debug'
        ExternalNuget: true